#!/bin/bash
#SBATCH --job-name=geneticfactorySim
#SBATCH --partition=paul
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=2GB
#SBATCH --time=24:00:00
#SBATCH --mail-type=BEGIN,END
#SBATCH --array=1-16%8
# array von 1  bis 16 und 8 Jobs gleichzeitg



apptainer exec --bind /work:/work "$HOME/factorySim/factorySim.sif" python3 -u geneticFactorySim.py --problemID "$SLURM_ARRAY_TASK_ID" --num-workers "$SLURM_CPUS_PER_TASK" --num-generations 2000 --num-population 300 --num-genmemory 0

# run with sbatch slurm-job.sh

