#!/bin/bash
#SBATCH --job-name=factorySim
#SBATCH --partition=clara
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
# --gpus-per-node=v100:1
#SBATCH --gpus-per-node=1
#SBATCH --mem-per-cpu=2GB
#SBATCH --time=24:00:00
#SBATCH --mail-type=BEGIN,END

#module load CUDA/12.1.1


#wandb could not wirte to tis directory
#ws_allocate wandb 5
#mkdir /work/hm631cryu-wandb/wandb

apptainer run --nv "$HOME/factorySim/factorySim.sif"

#clara cluster
# run with sbatch slurm-job.sh

