#!/bin/bash
#SBATCH --partition=paul,paula,clara
#SBATCH --job-name=FactorySimContainerBuilder
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1GB
#SBATCH --time=1:00:00


module load CUDA/12.6.0

set -euo pipefail

# Create workspace (10 days here)
WORKSPACE=$(ws_allocate "ray-${SLURM_JOB_ID}" 10 | grep -E '^/work/' | tail -n 1)
export WORKSPACE

export MY_RAY_RESULTS_DIR="$WORKSPACE/ray_results"
export RAY_TMPDIR="$WORKSPACE/ray_tmp"
export WANDB_DIR="$WORKSPACE/wandb"


mkdir -p "$RAY_RESULTS_DIR" "$WANDB_DIR" "$TMPDIR" 

echo "WORKSPACE=$WORKSPACE"
echo "RAY_RESULTS_DIR=$MY_RAY_RESULTS_DIR"
echo "WANDB_DIR=$WANDB_DIR"

apptainer exec --nv "$HOME/factorySim/factorySim.sif" python3 -u train.py -cid 83

#clara cluster
# run with sbatch slurm-buildContainer.job
#X2VQtEV?vmYH3S9KPS% 