#!/bin/bash
#SBATCH --job-name=geneticfactorySim
#SBATCH --partition=paul
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --mem-per-cpu=2GB
#SBATCH --time=24:00:00
#SBATCH --mail-type=BEGIN,END



apptainer exec --bind /work:/work "$HOME/factorySim/factorySim.sif" python3 -u geneticFactorySim.py --num-workers "$SLURM_CPUS_PER_TASK" --num-generations 2000 --num-population 300 --num-genmemory 0

# run with sbatch slurm-job.sh

