#!/bin/bash
#SBATCH --partition=clara
#SBATCH --job-name=FactorySimContainerBuilder
#SBATCH --ntasks=1
#SBATCH --cpus-per-tasks=12
#SBATCH --mem-per-cpu=1GB
#SBATCH --time=1:00:00
export SLURM_CPUS_PER_TASK=$SLURM_CPUS_PER_TASK


rm -R -f factorySim 

git clone https://github.com/hendrikunger/factorySim.git

cd ~/factorySim

srun apptainer build "$HOME/factorySim/factorysim.sif" "$HOME/factorySim/Singularity.def"
#clara cluster
# run with sbatch slurm-buildContainer.job